pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	// Loom 1.7.x is the line used for MC 1.21 / 1.21.1 mappings + run configs.
	id 'fabric-loom' version '1.7-SNAPSHOT'
}

rootProject.name = 'doomsday-nukes'
