package com.doomsday.nukes.network.packet;

import com.doomsday.nukes.DoomsdayNukes;
import net.minecraft.network.RegistryByteBuf;
import net.minecraft.network.codec.PacketCodec;
import net.minecraft.network.packet.CustomPayload;

/**
 * Chunk-granular contamination field around one player.
 *
 * <p><b>Why chunk-level, and why per-player.</b> Radiation needs a spatial field, but a
 * block-level field for a Tsar Bomba footprint is ~10^5 cells. A 16×16 column of fallout is
 * one float: the same footprint is a few hundred entries, i.e. a few kilobytes, and the
 * Geiger/HUD behaviour is indistinguishable at that resolution (contamination is generated by
 * the same chunk-quantised plan that writes it). Per-player because the useful field is only
 * what surrounds a given observer — a server broadcasting the whole global map to everyone
 * would be both wasteful and impossible to bound.</p>
 *
 * <p>Both arrays are length-prefixed and hard-capped at {@link #MAX_ENTRIES} on read, so a
 * malicious or corrupt packet can never allocate an unbounded array.</p>
 */
public record RadiationSyncS2CPacket(long[] chunkKeys, float[] doses) implements CustomPayload {
	/** Upper bound accepted from the wire; matches the server's own sync budget. */
	public static final int MAX_ENTRIES = 512;

	public static final CustomPayload.Id<RadiationSyncS2CPacket> ID =
		new CustomPayload.Id<>(DoomsdayNukes.id("radiation_sync"));

	public static final PacketCodec<RegistryByteBuf, RadiationSyncS2CPacket> CODEC =
		CustomPayload.codecOf((buf, payload) -> payload.writePayload(buf),
			RadiationSyncS2CPacket::read);

	@Override
	public CustomPayload.Id<? extends CustomPayload> getId() {
		return ID;
	}

	private void writePayload(RegistryByteBuf buf) {
		int n = Math.min(chunkKeys.length, doses.length);
		buf.writeVarInt(n);
		for (int i = 0; i < n; i++) {
			buf.writeLong(chunkKeys[i]);
			buf.writeFloat(doses[i]);
		}
	}

	private static RadiationSyncS2CPacket read(RegistryByteBuf buf) {
		int raw = buf.readVarInt();
		int n = Math.max(0, Math.min(raw, MAX_ENTRIES));
		long[] keys = new long[n];
		float[] vals = new float[n];
		for (int i = 0; i < n; i++) {
			keys[i] = buf.readLong();
			float v = buf.readFloat();
			// Clamp on read: the client uses these to drive a gauge and a damage rate.
			vals[i] = Float.isNaN(v) ? 0.0F : Math.max(0.0F, Math.min(1.0F, v));
		}
		// If the sender claimed more entries than we accept, drain the remainder so the
		// buffer position stays aligned for anything after this payload.
		for (int i = n; i < raw; i++) {
			if (!buf.isReadable(16)) {
				break;
			}
			buf.readLong();
			buf.readFloat();
		}
		return new RadiationSyncS2CPacket(keys, vals);
	}

	public int size() {
		return Math.min(chunkKeys.length, doses.length);
	}
}
